-- Flyway migration to support dynamic settings, architecture diagrams, and terminal commands

-- 1. Profiles/Settings
CREATE TABLE profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    title VARCHAR(150) NOT NULL,
    available_status VARCHAR(100),
    bio TEXT,
    resume_url VARCHAR(255),
    github_url VARCHAR(255),
    linkedin_url VARCHAR(255),
    email VARCHAR(100)
);

-- 2. Architecture Nodes
CREATE TABLE architecture_nodes (
    id VARCHAR(50) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    tech VARCHAR(100) NOT NULL,
    icon VARCHAR(50) NOT NULL,
    color VARCHAR(20) NOT NULL,
    title VARCHAR(150) NOT NULL,
    description TEXT NOT NULL,
    flow_sequence TEXT NOT NULL,
    connections VARCHAR(255)
);

-- 3. Terminal Commands
CREATE TABLE terminal_commands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    command_name VARCHAR(50) UNIQUE NOT NULL,
    type VARCHAR(20) NOT NULL,
    response_lines TEXT NOT NULL
);

-- 4. Initial Seed Data
INSERT INTO profiles (name, title, available_status, bio, resume_url, github_url, linkedin_url, email) VALUES
('Abhinandan Naik', 'Backend Java Engineer & Systems Architect', 'Available for Opportunities', 'Engineering scalable, high-throughput distributed architectures using Java, Spring Boot, SQL databases, and modern cloud deployment patterns. Currently engineering backend systems at Digit Insurance.', '/Abhinandan_Naik_Resume.pdf', 'https://github.com/abhinandan-naik', 'https://linkedin.com/in/abhinandan-naik', 'abhinandannaik1717@gmail.com');

INSERT INTO architecture_nodes (id, name, tech, icon, color, title, description, flow_sequence, connections) VALUES
('client', 'Client Layer', 'React / Next.js', 'cpu', '#8B5CF6', 'Client Layer — React / Next.js 15', 'Single-page application pre-rendered using static rendering and optimized using React 19. It serves static layout elements instantly and handles dynamic data fetching asynchronously via React Query.', 'User Action ➔ Next.js client intercepts ➔ Fires AJAX request to API Gateway', 'gateway'),
('gateway', 'API Gateway', 'Nginx Proxy', 'network', '#00F5FF', 'API Gateway — Nginx Reverse Proxy', 'The single entry checkpoint for all web requests. Offloads SSL handshakes, strips CORS headers, and routes `/api/**` traffic directly to Spring Boot backend services.', 'HTTPS Request ➔ SSL Decryption ➔ Header Sanitization ➔ Proxy Forward to Port 8888', 'auth,services'),
('auth', 'Auth Security', 'Spring Security / JWT', 'key', '#EF4444', 'Authentication Service — Security Context Filter', 'Stateless access authorization filter. Validates signature claims on incoming JWT tokens, handles admin credential matches via BCrypt, and injects user profiles into the Spring security context.', 'Filter checks authorization header ➔ Verifies RS256 JWT key claims ➔ Sets security session', 'services'),
('services', 'Core Services', 'Spring Boot 3.5', 'server', '#6366F1', 'Core Services — Spring Boot Business Logic', 'Processes business models and operations. Serves projects datasets, updates blog entries, captures analytical telemetries, and handles automated rate-limiting checks.', 'Processes logic ➔ Queries Redis Cache (Read-heavy) ➔ Queries Postgres (Write/Transactional)', 'cache,database'),
('cache', 'Cache Layer', 'Redis Memory Cache', 'zap', '#FBB324', 'Cache Layer — Redis Memory Storage', 'High-speed key-value cache. Stores frequently loaded assets and rate limit session trackers, reducing SQL fetch demands by up to 60%.', 'Check cache ➔ HIT: return cached JSON ➔ MISS: fetch DB ➔ write to cache ➔ return', ''),
('database', 'Database', 'PostgreSQL DB', 'database', '#22C55E', 'Database — PostgreSQL Storage', 'Persistent transactional database managed with Flyway schema versioning. Configured with optimized index tables on query slugs and composite timestamp logs.', 'Spring Boot JPA leases connection ➔ Runs parameterized queries ➔ Commits transaction', '');

INSERT INTO terminal_commands (command_name, type, response_lines) VALUES
('help', 'accent', 'Available commands:|  about      ➔ Detail developer profile|  skills     ➔ Tech stack & tool metrics|  experience ➔ Commercial work chronology|  projects   ➔ Featured engineering systems|  contact    ➔ Direct communication details|  resume     ➔ Download technical PDF CV|  clear      ➔ Wipe terminal buffer history|  easteregg  ➔ 🎯 Trigger hidden routine'),
('about', 'success', 'Name     : Abhinandan Naik|Role     : Full-Stack Software Engineer|Employer : Digit Insurance (Motor Insurance Division)|Degree   : BE (Hons.) Information Science & Engineering|Focus    : Scalable backend APIs, database tuning, and GenAI integrations|Languages: English, Hindi, Kannada|Status   : Open to full-stack software engineering engagements 🚀'),
('skills', 'accent', 'Backend  : Java, Spring Boot, Microservices, Security, REST APIs|Database : PostgreSQL, MySQL, Redis, DBeaver database tuning|DevOps   : Kubernetes, Bitbucket, Jenkins CI/CD, Dynatrace validation|Frontend : Next.js, Supabase, TypeScript, React, TailwindCSS'),
('experience', 'secondary', '[July 2025 - Present] Software Engineer @ Digit Insurance|  ➔ Architected scalable backend APIs for Motor Loader & Single Page modules|  ➔ Implemented Redis caching for bulk policy and payment processing|  ➔ Tuned complex database schemas in PostgreSQL to ensure integrity|  ➔ Automated deployment via Bitbucket & Jenkins, microservices in Kubernetes|  ➔ Monitored endpoints using Dynatrace and contributed to Agentic AI automation'),
('projects', 'success', '1. FlowSync ➔ AI-Powered Kanban Board (Next.js, Supabase, State Sync, AI Workflow)|2. FlashPoll ➔ Real-Time Voting Platform (Node.js, Express, Socket.io, Sessions)|3. Smart-Bin ➔ IoT Waste Manager (ESP8266, Sensor dashboard, Route optimization)'),
('contact', 'accent', 'Primary Email : abhinandannaik1717@gmail.com|LinkedIn Profile: linkedin.com/in/abhinandan-naik|GitHub Page    : github.com/abhinandan-naik|Availability   : ● ACTIVE FOR INTERVIEWS'),
('resume', 'success', 'Assembling technical credentials...|✓ Packaging latest database telemetry...|✓ Compiling PDF binary stream...|➔ Download initiated: Abhinandan_Naik_Resume.pdf 📄'),
('easteregg', 'secondary', '  ╔══════════════════════════════════════════════╗|  ║         EASTER EGG COMPILE SUCCESS 🎉        ║|  ║                                              ║|  ║   "Java is to JavaScript as car is to      ║|  ║    carpet." - Chris Heilmann                 ║|  ║                                              ║|  ║   Spring != Spring Boot                      ║|  ║   Docker != VM (Virtual Machine)             ║|  ╚══════════════════════════════════════════════╝');
