spring:
  profiles:
    active: local
  application:
    name: portfolio-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
  cache:
    type: caffeine
    caffeine:
      spec: expireAfterWrite=60s

server:
  port: 8080
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

# Custom JWT configuration
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  access-token-expiration: 900000 # 15 minutes in ms (15 * 60 * 1000)
  refresh-token-expiration: 604800000 # 7 days in ms (7 * 24 * 60 * 60 * 1000)

openai:
  api:
    key: ${OPENAI_API_KEY:}
